linux:
  image: python:3.8
  # make a docker daemon available for cibuildwheel to use
  services:
    - name: docker:dind
      entrypoint: ["env", "-u", "DOCKER_HOST"]
      command: ["dockerd-entrypoint.sh"]
  variables:
    DOCKER_HOST: tcp://docker:2375/
    DOCKER_DRIVER: overlay2
    # See https://github.com/docker-library/docker/pull/166
    DOCKER_TLS_CERTDIR: ""
  script:
    - curl -sSL https://get.docker.com/ | sh
    - python -m pip install cibuildwheel
    - cibuildwheel --output-dir wheelhouse
  artifacts:
    paths:
      - wheelhouse/

windows:
  tags:
    - shared-windows
    - windows
    - windows-1809
  script:
    - choco install python --version 3.8.5 -y
    - export PATH="/c/Python38:/c/Python38/Scripts:$PATH"
    - python -m pip install cibuildwheel
    - cibuildwheel --output-dir wheelhouse
  artifacts:
    paths:
      - wheelhouse/
